--------------------------------------------------------
--  Fichier créé - mercredi-juillet-17-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "AZIZ"."COMMANDE" 
   (	"REFERENCE_COMMANDE" NUMBER(*,0), 
	"METHODE_PAYEMENT" VARCHAR2(20 BYTE), 
	"DATE_COMMANCE" DATE, 
	"NUM_LISCENCE" NUMBER(*,0), 
	"NUM_COMPTE" NUMBER(*,0), 
	"STATUT" VARCHAR2(20 BYTE), 
	"CIN_CLIENT" NUMBER, 
	"CIN_TRANSPORTEUR" NUMBER, 
	"REF_PRODUIT" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZIZ.COMMANDE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMMANDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."COMMANDE_PK" ON "AZIZ"."COMMANDE" ("REFERENCE_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_PK" PRIMARY KEY ("REFERENCE_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "AZIZ"."COMMANDE" MODIFY ("REFERENCE_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK1" FOREIGN KEY ("CIN_CLIENT")
	  REFERENCES "AZIZ"."CLIENT" ("CIN") ENABLE;
 
  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK2" FOREIGN KEY ("CIN_TRANSPORTEUR")
	  REFERENCES "AZIZ"."TRANSPORTEUR" ("CIN") ENABLE;
 
  ALTER TABLE "AZIZ"."COMMANDE" ADD CONSTRAINT "COMMANDE_FK3" FOREIGN KEY ("REFERENCE_COMMANDE")
	  REFERENCES "AZIZ"."PRODUIT" ("REF") ENABLE;
