--------------------------------------------------------
--  Fichier créé - mercredi-juillet-17-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "AZIZ"."FOURNISSEUR" 
   (	"ID" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"TELEPHONE" LONG, 
	"PRODUIT" VARCHAR2(20 BYTE), 
	"NOTE" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AZIZ.FOURNISSEUR
SET DEFINE OFF;
Insert into AZIZ.FOURNISSEUR (ID,ADRESSE,TELEPHONE,PRODUIT,NOTE,EMAIL,NOM) values ('HP','menzah','992153546','ordinateur','4','hp.hp@gmail.com','hp');
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AZIZ"."FOURNISSEUR_PK" ON "AZIZ"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "AZIZ"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("ADRESSE" NOT NULL ENABLE);
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("TELEPHONE" NOT NULL ENABLE);
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("PRODUIT" NOT NULL ENABLE);
 
  ALTER TABLE "AZIZ"."FOURNISSEUR" MODIFY ("NOTE" NOT NULL ENABLE);
